/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSnippetsRouteImport } from './routes/dashboard.snippets'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardNotesRouteImport } from './routes/dashboard.notes'
import { Route as DashboardProjectIndexRouteImport } from './routes/dashboard.project.index'
import { Route as DashboardProjectIdRouteImport } from './routes/dashboard.project.$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSnippetsRoute = DashboardSnippetsRouteImport.update({
  id: '/snippets',
  path: '/snippets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotesRoute = DashboardNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectIndexRoute = DashboardProjectIndexRouteImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectIdRoute = DashboardProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/snippets': typeof DashboardSnippetsRoute
  '/dashboard/project/$id': typeof DashboardProjectIdRoute
  '/dashboard/project/': typeof DashboardProjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/snippets': typeof DashboardSnippetsRoute
  '/dashboard/project/$id': typeof DashboardProjectIdRoute
  '/dashboard/project': typeof DashboardProjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/snippets': typeof DashboardSnippetsRoute
  '/dashboard/project/$id': typeof DashboardProjectIdRoute
  '/dashboard/project/': typeof DashboardProjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/dashboard/notes'
    | '/dashboard/settings'
    | '/dashboard/snippets'
    | '/dashboard/project/$id'
    | '/dashboard/project/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/dashboard/notes'
    | '/dashboard/settings'
    | '/dashboard/snippets'
    | '/dashboard/project/$id'
    | '/dashboard/project'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/dashboard/notes'
    | '/dashboard/settings'
    | '/dashboard/snippets'
    | '/dashboard/project/$id'
    | '/dashboard/project/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/snippets': {
      id: '/dashboard/snippets'
      path: '/snippets'
      fullPath: '/dashboard/snippets'
      preLoaderRoute: typeof DashboardSnippetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notes': {
      id: '/dashboard/notes'
      path: '/notes'
      fullPath: '/dashboard/notes'
      preLoaderRoute: typeof DashboardNotesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/project/': {
      id: '/dashboard/project/'
      path: '/project'
      fullPath: '/dashboard/project/'
      preLoaderRoute: typeof DashboardProjectIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/project/$id': {
      id: '/dashboard/project/$id'
      path: '/project/$id'
      fullPath: '/dashboard/project/$id'
      preLoaderRoute: typeof DashboardProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardNotesRoute: typeof DashboardNotesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSnippetsRoute: typeof DashboardSnippetsRoute
  DashboardProjectIdRoute: typeof DashboardProjectIdRoute
  DashboardProjectIndexRoute: typeof DashboardProjectIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardNotesRoute: DashboardNotesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSnippetsRoute: DashboardSnippetsRoute,
  DashboardProjectIdRoute: DashboardProjectIdRoute,
  DashboardProjectIndexRoute: DashboardProjectIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
